;;; Autogenerated by Thrift
;;; DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
;;; options string: cl

(asdf:defsystem #:thrift-gen-common
  :depends-on (:thrift)
  :serial t
  :components ((:file "common-types") (:file "common-vars")))
