;;; Autogenerated by Thrift
;;; DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
;;; options string: cl

(asdf:defsystem #:thrift-gen-extension_functions
  :depends-on (:thrift)
  :serial t
  :components ((:file "extension_functions-types") (:file "extension_functions-vars")))
