;;; Autogenerated by Thrift
;;; DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
;;; options string: cl

(asdf:defsystem #:thrift-gen-heavy
  :depends-on (:thrift :thrift-gen-common :thrift-gen-completion_hints :thrift-gen-serialized_result_set :thrift-gen-extension_functions)
  :serial t
  :components ((:file "heavy-types") (:file "heavy-vars")))
