;;; Autogenerated by Thrift
;;; DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
;;; options string: cl

(thrift:def-package :thrift-generated)

(cl:in-package :thrift-generated)

(thrift:def-enum "TCompletionHintType"
  (("COLUMN" . 0)
   ("TABLE" . 1)
   ("VIEW" . 2)
   ("SCHEMA" . 3)
   ("CATALOG" . 4)
   ("REPOSITORY" . 5)
   ("FUNCTION" . 6)
   ("KEYWORD" . 7)))

(thrift:def-struct "tcompletionhint"
  (("type" nil :id 1 :type (enum "TCompletionHintType"))
   ("hints" nil :id 2 :type (thrift:list string))
   ("replaced" nil :id 3 :type string)))

