;;; Autogenerated by Thrift
;;; DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
;;; options string: cl

(asdf:defsystem #:thrift-gen-completion_hints
  :depends-on (:thrift)
  :serial t
  :components ((:file "completion_hints-types") (:file "completion_hints-vars")))
